# Generated by Django 4.0.2 on 2022-03-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computerbrands',
            old_name='name',
            new_name='brandname',
        ),
    ]
