# Generated by Django 4.0.2 on 2022-03-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_rename_name_computerbrands_brandname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=50)),
                ('price_min', models.IntegerField(max_length=50)),
                ('price_max', models.IntegerField(max_length=50)),
                ('ram', models.IntegerField(max_length=50)),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.computerbrands')),
            ],
        ),
    ]
