# Generated by Django 4.0.2 on 2022-03-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_computerspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerspecification',
            name='price_max',
            field=models.IntegerField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='price_min',
            field=models.IntegerField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='ram',
            field=models.IntegerField(verbose_name=50),
        ),
    ]
