# Generated by Django 4.0.2 on 2022-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0006_computerspecification_computercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computercode', models.CharField(blank=True, max_length=50, null=True)),
                ('brandname', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=5)),
                ('unitrate', models.CharField(default='', max_length=50)),
                ('totalprice', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
