# Generated by Django 4.0.2 on 2022-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='computercode',
            field=models.IntegerField(default=0),
        ),
    ]
