# Generated by Django 4.0.2 on 2022-03-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0008_alter_order_computercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='computercode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
