# Generated by Django 4.0.2 on 2022-03-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0009_alter_order_computercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='computercode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
